<?php

namespace App\Http\Controllers\Payment;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Library\NicepayLib;

class RequestCPay extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function __invoke(Request $request)
    {
        $nicepay = new NicepayLib();

// Generate Reference Number
        function generateReference()
        {
            $micro_date = microtime();
            $date_array = explode(" ",$micro_date);
            $date = date("YmdHis",$date_array[1]);
            $date_array[0] = preg_replace('/[^\p{L}\p{N}\s]/u', '', $date_array[0]);
            return "Ref".$date.$date_array[0].rand(100,999);
        }

        $payMethod = $request->input('payMethod');
        $referenceNo = $request->input('referenceNo');
        if(isset($payMethod) && $payMethod == '04'){

            // Populate Mandatory parameters to send
            $nicepay->set('payMethod', '04');
            $nicepay->set('currency', 'IDR');

            if(!isset($referenceNo) || $referenceNo == null){
                $nicepay->set('referenceNo', generateReference()); // Invoice Number or Reference Number Generated by merchant
            }else{
                $nicepay->set('referenceNo', $referenceNo);
            }

            $nicepay->set('amt', $request->input('amt')); // Total gross amount
            $nicepay->set('paymentExpDt', $request->input('paymentExpDt')); // Total gross amount
            $nicepay->set('paymentExpTm', $request->input('paymentExpTm')); // Total gross amount
            $nicepay->set('description', 'Payment of Invoice No '.$nicepay->get('referenceNo')); // Transaction description

            $nicepay->set('billingNm', 'John Doe'); // Customer name
            $nicepay->set('billingPhone', '02112345678'); // Customer phone number
            $nicepay->set('billingEmail', 'john@example.com'); // Customer Email
            $nicepay->set('billingAddr', 'Jl. Jend. Sudirman No. 28');
            $nicepay->set('billingCity', 'Jakarta Pusat');
            $nicepay->set('billingState', 'DKI Jakarta');
            $nicepay->set('billingPostCd', '10210');
            $nicepay->set('billingCountry', 'Indonesia');

            $nicepay->set('deliveryNm', 'John Doe'); // Delivery name
            $nicepay->set('deliveryPhone', '02112345678');
            $nicepay->set('deliveryEmail', 'john@example.com');
            $nicepay->set('deliveryAddr', 'Jl. Jend. Sudirman No. 28');
            $nicepay->set('deliveryCity', 'Jakarta Pusat');
            $nicepay->set('deliveryState', 'DKI Jakarta');
            $nicepay->set('deliveryPostCd', '10210');
            $nicepay->set('deliveryCountry', 'Indonesia');

            // Send Data
            $response = $nicepay->requestVA();

            // Response from NICEPAY
            if (isset($response->data->resultCd) && $response->data->resultCd == "0000") {
                session(['payMethod' => '04']);
                return redirect()->away($response->data->requestURL . "?tXid=" . $response->tXid);
            } elseif (isset($response->data->resultCd)) {
                $msg = $response->data->resultCd . ": " . $response->data->resultMsg;
                $request->session()->flash('msg', $msg);
                return redirect()->route('otherError');
            } else {
                $request->session()->flash('msg', 'Connection Timeout. Please Try Again!');
                return redirect()->route('otherError');
            }
        } // Unknown Pay Method
        else {
            $request->session()->flash('msg', 'Please Set Amount, ReferenceNo and tXid.');
            return redirect()->route('otherError');
        }
    }
}
