<?php

namespace App\Http\Controllers\Payment;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Library\NicepayLib;
use App\Models\Address;
use App\Models\Product;

class RequestEWallet extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function __invoke(Request $request)
    {
        $nicepay = new NicepayLib();

        $products = collect(request('product'));
        $cartData['count'] = $products->count() + 1;
        $cartData['item'] = $products->map(function($value, $key){
            $product = Product::find($value);
            return [
                'img_url'       => 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone11-select-2019-family?wid=882&amp;hei=1058&amp;fmt=jpeg&amp;qlt=80&amp;op_usm=0.5,0.5&amp;.v=1567022175704',
                'goods_name'    => $product->title,
                'goods_detail'  => $product->description,
                'goods_amt'     => $product->price * request('quantity')[$key]

            ];
        });

        $cartData['item'][] = [
            'img_url'       => 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone11-select-2019-family?wid=882&amp;hei=1058&amp;fmt=jpeg&amp;qlt=80&amp;op_usm=0.5,0.5&amp;.v=1567022175704',
            'goods_name'    => 'Ongkos Pengiriman',
            'goods_detail'  => 'Biaya Ongkos Pengiriman paket',
            'goods_amt'     => 10000
        ];
        
        $user = auth()->user();
        $address = Address::find(request('address_id'));
        
        function generateReference()
        {
            $micro_date = microtime();
            $date_array = explode(" ",$micro_date);
            $date = date("YmdHis",$date_array[1]);
            $date_array[0] = preg_replace('/[^\p{L}\p{N}\s]/u', '', $date_array[0]);
            return "Ref".$date.$date_array[0].rand(100,999);
        }
        $payMethod = $request->input('payMethod');
        $referenceNo = $request->input('referenceNo');
        if(isset($payMethod) && $payMethod == '05'){

            // Populate Mandatory parameters to send
            $nicepay->set('payMethod', '05');
            $nicepay->set('currency', 'IDR');

            if(!isset($referenceNo) || $referenceNo == null){
                $nicepay->set('referenceNo', generateReference()); // Invoice Number or Reference Number Generated by merchant
            }else{
                $nicepay->set('referenceNo', $referenceNo);
            }
            $nicepay->set('cartData', json_encode($cartData));
            $nicepay->set('amt', $request->input('amt')); // Total gross amount
            $nicepay->set('paymentExpDt', $request->input('paymentExpDt')); // Total gross amount
            $nicepay->set('paymentExpTm', $request->input('paymentExpTm')); // Total gross amount
            $nicepay->set('description', 'Payment of Invoice No '.$nicepay->get('referenceNo')); // Transaction description

            $nicepay->set('billingNm', $user->name); // Customer name
            $nicepay->set('billingPhone', $user->phone); // Customer phone number
            $nicepay->set('billingEmail', $user->email); // Customer Email
            $nicepay->set('billingAddr', $address->detail);
            $nicepay->set('billingCity', $address->regency->name);
            $nicepay->set('billingState', $address->province->name);
            $nicepay->set('billingPostCd', $address->postal_code);
            $nicepay->set('billingCountry', 'Indonesia');

            $nicepay->set('deliveryNm', 'John Doe'); // Delivery name
            $nicepay->set('deliveryPhone', '02112345678');
            $nicepay->set('deliveryEmail', 'john@example.com');
            $nicepay->set('deliveryAddr', 'Jl. Jend. Sudirman No. 28');
            $nicepay->set('deliveryCity', 'Jakarta Pusat');
            $nicepay->set('deliveryState', 'DKI Jakarta');
            $nicepay->set('deliveryPostCd', '10210');
            $nicepay->set('deliveryCountry', 'Indonesia');

            // Send Data
            $response = $nicepay->requestEWallet();

            // Response from NICEPAY
            if (isset($response->data->resultCd) && $response->data->resultCd == "0000") {
                session(['payMethod' => '05']);
                return redirect()->away($response->data->requestURL . "?tXid=" . $response->tXid);
            } elseif (isset($response->data->resultCd)) {
                $msg = $response->data->resultCd . ": " . $response->data->resultMsg;
                $request->session()->flash('msg', $msg);
                // return redirect()->route('otherError');
                return $msg;
            } else {
                return 'Connection Timeout. Please Try Again!';
                // $request->session()->flash('msg', 'Connection Timeout. Please Try Again!');
                // return redirect()->route('otherError');
            }
        } // Unknown Pay Method
        else {
            // $request->session()->flash('msg', 'Please Set Amount, ReferenceNo and tXid.');
            // return redirect()->route('otherError');
            return 'Please Set Amount, ReferenceNo and tXid.';
        }
    }
}
